### ISSUE TITLE
Map does not display

### ISSUE THREAD

**Issue by OmenApps** [nnseva/django-leaflet-admin-list#4]
I use django-leaflet a lot in my app, and it works great. But for some reason with this package I get no errors (in either python console or js console), but no map. There's a map-sized empty space in the admin list_display, but no map and no clear way to troubleshoot the issue.

I can see that all of the media static files are loading fine, and even that the tiles and map market icon load in the browser's Network tab.

My admin class is pretty straightforward:

```
@admin.register(NetworkNode)
class NodePointAdmin(LeafletAdminListMixin, LeafletGeoAdminMixin, admin.ModelAdmin):
    list_display = [
        "id",
        "pkid",
        "created",
        "modified",
        "modified_by",
        "minimum_flow",
        "maximum_flow",
        "point",
        "is_active",
        "is_supply_point",
        "sort_order",
    ]
```

Any thoughts on where to go from here? With no errors popping up, it's unclear how I might approach this. I am using Grapelli in my admin. Could there be a conflict? Let me know what other information I could provide to clarify the issue.

**Comment by nnseva** [comment]
Hi @OmenApps, please update to v.0.0.3 from the PyPi or just from the repository

**Comment by nnseva** [comment]
looks like fixed
